# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  pull_request:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: enable Npm with corepack
        run: corepack enable pnpm

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: pNpm install
        run: pnpm install

# 1. Install the standalone reviewdog binary on the runner
      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run ESLint with Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm exec eslint . -f stylish | reviewdog -f=eslint -reporter=github-pr-check -level=error
